### ISSUE TITLE
Running original EuRoC rosbags

### ISSUE THREAD

**Issue by chen12345678910** [VIS4ROB-lab/pose_graph_backend#3]
I want to run multi-agent on the original euroc dataset. How do I implement it?

**Comment by lucaBartolomei** [comment]
Hi,
have you check [these instructions](https://github.com/VIS4ROB-lab/pose_graph_backend#12-multi-agent), or are you trying to do something different?

**Comment by chen12345678910** [comment]
I want to use the euroc data set downloaded from the website instead of the data set in pose_graph_backend,how can I do this?

**Comment by lucaBartolomei** [comment]
So you want to run the pose graph using the original EuRoC rosbags, right? This is possible, it will just require a minimal adaptation of the instructions in the README. 

Similarly to the [general case](https://github.com/VIS4ROB-lab/pose_graph_backend#2-general-usage), you will need to do the following:
- When running the pose graph backend, specify the number of agents you need
- Run the `vins_estimator` and `pcl_fusion` nodes for each agent, specifying the IDs of the agents
- Play the EuRoC rosbags using the launch files `pose_graph_backend/launch/multi_agent_play_0.launch` specifying the path to the rosbags (of course, you will need to run this launch file for each agent)

I hope this gets you started.

**Comment by lucaBartolomei** [comment]
Closing this issue because it's inactive - feel free to re-open it in case you need additional help.
