### ISSUE TITLE
Got stuck at "params.voc_ptr = std::make_shared<BRISKVocabulary>(bow_voc_file)" in parameter-reader.cpp

### ISSUE THREAD

**Issue by Janebek** [VIS4ROB-lab/pose_graph_backend#5]
Hi thank you for your great work!

I'm trying to build a project on top of pose_graph_backend, but somehow I can not initialize the node i.e can not establish topics.

So when i am debugging, I find that whole system got stuck at "params.voc_ptr = std::make_shared<BRISKVocabulary>(bow_voc_file)" in parameter-reader.cpp, I don't know what happened, could you please help me on this?

By the way, I'm using Ubuntu 20 noetic.Really looking forward to your reply!

**Comment by lucaBartolomei** [comment]
Hi!

Could you please provide more information about what you are trying to do? 
Did you manage to download and build this repository correctly?

If so, you could have a look at our code and try to replicate on your side.

**Comment by Janebek** [comment]
Hi Luca!

I already solved this problem, it is because of the OpenCV version conflict.

Thanks for replying!
