### ISSUE TITLE
How to run it without gps?

### ISSUE THREAD

**Issue by Janebek** [VIS4ROB-lab/pose_graph_backend#7]
Hi Luca! 

Great work of yours!

I'm tring to run voxblox multi agent in a real world demo, but I also want to do it without gps i.e using pure VIO. I want to let those agents to gradually merge into one map like ccm-slam or covins did. And I find pose_graph_backend is capable of doing this, because it has a map merging function.

So Luca, do you have any suggestions on how to modify this? Or is there some way I can fake this gps thing using pure visual-inertial odometry?

I'm really looking forward to your rely! Thank you!

**Comment by lucaBartolomei** [comment]
Hi!

Thanks for the interest in the project. Unfortunately the whole pipeline strongly depends on the presence of GPS. In case you want to use the code as is, there is the possibility to use a fake GPS signal (susbcriber [here](https://github.com/VIS4ROB-lab/pose_graph_backend/blob/61d8079899323b6edbe3a3949e516dede931ef24/src/subscriber.cpp#L84)). This was for example done when testing the pipeline with the EuRoC dataset, where we used the Leica information as some sort of GPS.

Another option would be to change the cost functions to remove the part related to GPS (see Eq. 8 in the [paper](https://lucabartolomei.github.io/publications/IROS_2020_Multi_Robot.pdf)). However, this process is more involved and error prone and would change the nature of the pipeline (so I don't really recommend that).

Another way would be to use Maplab for that (but you'll need to pre-map the space and then the robots will just relocalize).

I hope this helps!

**Comment by Janebek** [comment]
Thanks for replying!

So I guess the only way to remove GPS part correctly is to change the cost function and the pipeline, although this might require a lot of work.

As for maplap, I wonder if it has a map merging function i.e. it can merge pre-mapped maps into one big map?

**Comment by lucaBartolomei** [comment]
I think it is able to do that. You'll need to do some processing offline after map collection, but map merging is one of Maplab's core functionalities. The best way to check this would be to check their github repos

**Comment by Janebek** [comment]
OK. I will check it, thank you Luca!
