### ISSUE TITLE
How to measure bandwith?

### ISSUE THREAD

**Issue by Janebek** [VIS4ROB-lab/pose_graph_backend#8]
Hi Luca!

I'm trying to reproduce some experiment results from your paper.

But when I measure the bandwith of keyframe topic using ' rostopic bw ' , the mean bandwith is around 100KB/s, not 24KB/s as your paper says. 

So I'm wondering maybe I used the wrong tool to measure the bandwith, my question is that what is the tool you used for measuring bandwith? 

I'm really looking forward to your reply! Thank you!

**Comment by lucaBartolomei** [comment]
Hi,

Sorry for the slow reply. This was quite some time ago, so I don't remember
exactly what we did. Most likely, we used `rostopic bw` as you did in one
experiment, collected all the outputs and then calculated the average/stdev
of the averages.

Il giorno sab 18 nov 2023 alle ore 17:38 Janebek ***@***.***>
ha scritto:

**Comment by Janebek** [comment]
Thank you Luca! Glad I'm doing it right!
